### ISSUE TITLE
Cant launch new v.1.7.0 AppImage

### ISSUE THREAD

**Issue by danrobi11** [irislib/iris-electron#16]
I could not copy, so I took a screenshot. And that's the shell output. Weird output ;)

```
./Iris-1.7.0.AppImage
Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!

```
![iris-1 7 0 issue](https://user-images.githubusercontent.com/48020114/116361380-eca0e100-a7ce-11eb-8d7c-9df5bcadd468.png)

**Comment by danrobi11** [comment]
I installed `libnatpmp-dev` but same result

**Comment by danrobi11** [comment]
Same with 1.7.1 appimage

**Comment by manning-ncsa** [comment]
I have a very similar issue with v1.7.1. I cannot start the app from the downloaded AppImage (same error message shown above), but when I build from source I can start it once. Upon startup, however, it automatically downloads an "update" (the published  v1.7.1 AppImage file) such that I cannot start the app again.

**Comment by anaqreon** [comment]
I created https://github.com/irislib/iris-electron/pull/18 to help solve this.

**Comment by danrobi11** [comment]
Working fine here with `Iris-2.0.3.AppImage` Therefore closing
