### ISSUE TITLE
Javascript error at launch with new v2.1.1

### ISSUE THREAD

**Issue by danrobi11** [irislib/iris-electron#26]
I cant copy the error so I had to screenshot it. Although, the app does launch and run. 

AppImage v2.1.1
MX 19.4 patito feo. Debian GNU/Linux 10 (buster

![Iris-electron](https://user-images.githubusercontent.com/48020114/130459707-742e2ed9-e166-4eb6-8b84-f9b32936a600.png)

**Comment by mmalmi** [comment]
I just removed release 2.1.1 because of these errors.
