### ISSUE TITLE
Java issue with appimage

### ISSUE THREAD

**Issue by danrobi11** [irislib/iris-electron#8]
![iris-electron issue](https://user-images.githubusercontent.com/48020114/107592926-33be0380-6bdc-11eb-834c-fe1a0688fc20.png)

Iris-1.5.7.AppImage
OS: MX 19.3 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
SysV init version: 2.93
Kernel: 4.19.0-9-amd64
Xorg v1:7.7+19
WM: Spectrwm

**Comment by mmalmi** [comment]
Thanks for reporting. Public-ip was added in this version, so the previous one should still work.

**Comment by mmalmi** [comment]
@danrobi11 can you test if v1.6.0 works any better? Updated electron and build tools.

**Comment by danrobi11** [comment]
Yes fixed. Thank you! Therefore closing.
