### ISSUE TITLE
Issue sync between users

### ISSUE THREAD

**Issue by danrobi11** [irislib/iris-electron#9]
I have sync issue with message and home section.
Im testing between my laptop and desktop on same local network.

Message section contact show offline and message sync is not good. Missing msg and/or take very long.
Same in the home section. Adding a msg on a post hasnt synced yet here.

I wonder it might be firewall related. Whats the ports I need to open to test? Is it persistent or new ports at every launch? From what Im seeing its tcp only, correct?

**Comment by mmalmi** [comment]
It should sync over multicast (udp) locally, but obviously it's not working if users on the same network appear offline. 

Do you see "+ http://localhost:8767/gun" in your peers? Electron frontend connects to the node.js backend which does the multicasting.

It may also be some other gun related issue — we're hoping that the next gun release fixes many of these random issues. One thing I noticed is that iris-electron on windows doesn't seem to persist data locally.

**Comment by danrobi11** [comment]
> Do you see "+ http://localhost:8767/gun" in your peers?

Yes I do.

Comment loss also happens. I commented under a post. That comment does not show up on any of my devices.

**Comment by danrobi11** [comment]
Hi
I just tested the webapp for a few hrs.

Webapp have the worst sync. I've tested with both of my devices.
The webapp does not find any of my ID's. I've created this far 4 ID's. 2 ID's with the webapp and another 2 ID's with the electron desktop. Webapp doesnt find any. At least the electron desktop ID's sees eachothers, but they dont see the webapp ID's either.

Is the webapp completely seperated network ? Whats going on ?

**Comment by danrobi11** [comment]
OK after further testing with friends.
Electron app seems to work better than the webapp.
Most sync issue that I see is syncing the comments of comments. (Commenting comments) That takes quite long to sync.
Post, Likes and private messages, they sync pretty good.

**Comment by danrobi11** [comment]
Overall sync is better with the version 1.6.2
Of course it can be better but it works now. Therefore closing.
